version: '3.7'
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: ttc
    volumes:
      - ./scripts/db-init/:/docker-entrypoint-initdb.d/
  scraper:
    build:
      context: .
    command: ["scrape"]
    depends_on:
      - db
    volumes:
      - .:/opt/ttc/subway_times/
