version: 2
jobs:
  linters:
    docker:
      - image: python:3.6.6-slim

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            export PATH="$HOME/.local/bin:$PATH"
            pip install --user tox

      - run:
          name: linters
          command: |
            export PATH="$HOME/.local/bin:$PATH"
            tox -e linters


workflows:
  version: 2
  workflow:
    jobs:
      - linters
      # - py33
      # - py34
      # - py35
      # - py36
      # - py37
