version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: linters
          command: tox -e linters
