version: 2.1
commands:
  install_deps:
    steps:
      - run: pip install --user tox

jobs:
  linters:
    docker:
      - image: python:3.6-slim
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: tox -e linters

  py33:
    docker:
      - image: python:3.3-slim
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: tox -e py33


workflows:
  version: 2
  workflow:
    jobs:
      - linters
      - py33
      # - py34
      # - py35
      # - py36
      # - py37
