version: 2.1
commands:
  tox:
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          pip install --user tox
          tox -e << parameters.env >>

jobs:
  linters:
    docker:
      - image: python:3.6-slim
    working_directory: ~/repo
    steps:
      - tox:
          env: linters

  py33:
    docker:
      - image: python:3.3-slim
    working_directory: ~/repo
    steps:
      - tox:
          env: py33


workflows:
  version: 2
  workflow:
    jobs:
      - linters
      - py33
      # - py34
      # - py35
      # - py36
      # - py37
